// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Context;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(MoziDbContext))]
    [Migration("20260305124617_mssql_migration_388")]
    partial class mssql_migration_388
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.24");

            modelBuilder.Entity("backend.Models.Felhasznalo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Jelszo")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Felhasznalo_Email_Unique");

                    b.ToTable("Felhasznalok");
                });

            modelBuilder.Entity("backend.Models.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cim")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Hossz")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Leiras")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rendezo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Cim")
                        .HasDatabaseName("IX_Film_Cim");

                    b.ToTable("Filmek");
                });

            modelBuilder.Entity("backend.Models.Foglalas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FelhasznaloId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FelhasznaloId")
                        .HasDatabaseName("IX_Foglalas_FelhasznaloId");

                    b.ToTable("Foglalasok");
                });

            modelBuilder.Entity("backend.Models.Foglalthely", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FoglalasId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SzekId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VetitesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FoglalasId");

                    b.HasIndex("SzekId");

                    b.HasIndex("VetitesId", "SzekId")
                        .IsUnique()
                        .HasDatabaseName("IX_Foglalthely_Vetites_Szek_Unique");

                    b.ToTable("Foglalthelyek");
                });

            modelBuilder.Entity("backend.Models.Szek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<char>("Oldal")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Szam")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeremId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeremId");

                    b.ToTable("Szekek");
                });

            modelBuilder.Entity("backend.Models.Terem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TeremNev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Termek");
                });

            modelBuilder.Entity("backend.Models.Vetites", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilmId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Idopont")
                        .HasColumnType("TEXT");

                    b.Property<int>("JegyAr")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nyelv")
                        .HasColumnType("TEXT");

                    b.Property<int>("TeremId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VetitesTipus")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Idopont")
                        .HasDatabaseName("IX_Vetites_Idopont");

                    b.HasIndex("FilmId", "Idopont")
                        .HasDatabaseName("IX_Vetites_FilmId_Idopont");

                    b.HasIndex("TeremId", "Idopont")
                        .HasDatabaseName("IX_Vetites_TeremId_Idopont");

                    b.ToTable("Vetitesek");
                });

            modelBuilder.Entity("backend.Models.Foglalas", b =>
                {
                    b.HasOne("backend.Models.Felhasznalo", "Felhasznalo")
                        .WithMany("Foglalasok")
                        .HasForeignKey("FelhasznaloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Felhasznalo");
                });

            modelBuilder.Entity("backend.Models.Foglalthely", b =>
                {
                    b.HasOne("backend.Models.Foglalas", "Foglalas")
                        .WithMany("Foglalthely")
                        .HasForeignKey("FoglalasId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Szek", "Szek")
                        .WithMany("Foglalthely")
                        .HasForeignKey("SzekId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Vetites", "Vetites")
                        .WithMany("Foglalthely")
                        .HasForeignKey("VetitesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Foglalas");

                    b.Navigation("Szek");

                    b.Navigation("Vetites");
                });

            modelBuilder.Entity("backend.Models.Szek", b =>
                {
                    b.HasOne("backend.Models.Terem", "Terem")
                        .WithMany("Szekek")
                        .HasForeignKey("TeremId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Terem");
                });

            modelBuilder.Entity("backend.Models.Vetites", b =>
                {
                    b.HasOne("backend.Models.Film", "Film")
                        .WithMany("Vetitesek")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Terem", "Terem")
                        .WithMany("Vetitesek")
                        .HasForeignKey("TeremId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Terem");
                });

            modelBuilder.Entity("backend.Models.Felhasznalo", b =>
                {
                    b.Navigation("Foglalasok");
                });

            modelBuilder.Entity("backend.Models.Film", b =>
                {
                    b.Navigation("Vetitesek");
                });

            modelBuilder.Entity("backend.Models.Foglalas", b =>
                {
                    b.Navigation("Foglalthely");
                });

            modelBuilder.Entity("backend.Models.Szek", b =>
                {
                    b.Navigation("Foglalthely");
                });

            modelBuilder.Entity("backend.Models.Terem", b =>
                {
                    b.Navigation("Szekek");

                    b.Navigation("Vetitesek");
                });

            modelBuilder.Entity("backend.Models.Vetites", b =>
                {
                    b.Navigation("Foglalthely");
                });
#pragma warning restore 612, 618
        }
    }
}
